spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: eisha
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

api:
  security:
    ignored: /swagger-ui/**,/v3/api-docs,/v3/api-docs/**,/h2-console/**,/v1/auth/login