spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:bank
    username: test
    password: ${DB_TEST_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false